### ISSUE TITLE
Execution of verify_files_are_present() failed

### ISSUE THREAD

**Issue by shenxianpeng** [shenxianpeng/cpp-linter-action#23]
I'd like to test `shenxianpeng/cpp-linter-action@master-py` in my test repository [test-cpp-linter-action](https://github.com/shenxianpeng/test-cpp-linter-action) and it failed with the following error message:

```bash
INFO:CPP Linter:File names:
	helloworld.cpp
INFO:CPP Linter:Downloading file from url: https://github.com/shenxianpeng/test-cpp-linter-action/raw/122b581c15688edbb8ba02079e8821a6725b263b/helloworld.cpp
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/python_action/run.py", line 500, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/python_action/run.py", line 492, in main
    verify_files_are_present()
  File "/usr/local/lib/python3.8/dist-packages/python_action/run.py", line 212, in verify_files_are_present
    temp.write(download)
TypeError: write() argument must be str, not Response
```
The completed log can be found here: https://github.com/shenxianpeng/test-cpp-linter-action/runs/3776570178

**Comment by 2bndy5** [comment]
I put in a possible fix for this on the master-py branch. Try re-running the test workflow

**Comment by shenxianpeng** [comment]
Tested this Test passed and closed.
