### ISSUE TITLE
Add support for private repos when fetching files in run.py

### ISSUE THREAD

**Issue by JosephDrazen** [shenxianpeng/cpp-linter-action#38]
It does not look like the code in run.py `get_list_of_changed_files` fetches with the given token. 

Wondering if this is a known problem and something that can be fixed? 

Getting the following error when fetching files from a private repo: 

```INFO:CPP Linter:Fetching files list from url: https://api.github.com/repos/myRepo
  Traceback (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.8/dist-packages/cpp_linter/run.py", line 764, in <module>
      main()
    File "/usr/local/lib/python3.8/dist-packages/cpp_linter/run.py", line 738, in main
      exit_early = not filter_out_non_source_files(
    File "/usr/local/lib/python3.8/dist-packages/cpp_linter/run.py", line 2[25](https://github.com/JosephDrazen/myRepo/runs/<run_id>?check_suite_focus=true#step:4:25), in filter_out_non_source_files
      os.path.splitext(file["filename"])[1][1:] in ext_list
  TypeError: string indices must be integers```

**Comment by 2bndy5** [comment]
We welcome PRs. I don't have a private repo to test this action on.

**Comment by 2bndy5** [comment]
I think a modification could be made to [`get_list_of_changed_files()`](https://github.com/shenxianpeng/cpp-linter-action/blob/b02b7fefb73fb1e6d9784c727e68e2458e2af26a/cpp_linter/run.py#L187) to conditionally pass the given token (if supplied).

It looks like the `requests()` call should be supplied with an `accept="application/vnd.github.v3+json "` arg in the header. I don't see a way to use the token for getting a list of files in a PR (or push) event. Note, the REST API docs have changed a bit since I wrote the code here.

**Comment by shenxianpeng** [comment]
Close this issue as it has been implemented in https://github.com/shenxianpeng/cpp-linter-action/pull/40, any feedback on this is welcome.
